#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xEB6CCA1483FA74EC (infra-root@openstack.org)
#
Name     : oslo.service
Version  : 1.21.0
Release  : 32
URL      : http://tarballs.openstack.org/oslo.service/oslo.service-1.21.0.tar.gz
Source0  : http://tarballs.openstack.org/oslo.service/oslo.service-1.21.0.tar.gz
Source99 : http://tarballs.openstack.org/oslo.service/oslo.service-1.21.0.tar.gz.asc
Summary  : oslo.service library
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.service-python
Requires: Paste
Requires: PasteDeploy
Requires: Routes
Requires: WebOb
Requires: eventlet
Requires: greenlet
Requires: monotonic
Requires: oslo.concurrency
Requires: oslo.config
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.utils
Requires: six
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
========================
Team and repository tags
========================
.. image:: http://governance.openstack.org/badges/oslo.service.svg
:target: http://governance.openstack.org/reference/tags/index.html

%package python
Summary: python components for the oslo.service package.
Group: Default

%description python
python components for the oslo.service package.


%prep
%setup -q -n oslo.service-1.21.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1490884476
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1490884476
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
