#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xFC43F0EE211DFED8 (infra-root@openstack.org)
#
Name     : oslo.service
Version  : 1.40.2
Release  : 56
URL      : http://tarballs.openstack.org/oslo.service/oslo.service-1.40.2.tar.gz
Source0  : http://tarballs.openstack.org/oslo.service/oslo.service-1.40.2.tar.gz
Source1 : http://tarballs.openstack.org/oslo.service/oslo.service-1.40.2.tar.gz.asc
Summary  : oslo.service library
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.service-license = %{version}-%{release}
Requires: oslo.service-python = %{version}-%{release}
Requires: oslo.service-python3 = %{version}-%{release}
Requires: Paste
Requires: PasteDeploy
Requires: Routes
Requires: WebOb
Requires: debtcollector
Requires: eventlet
Requires: fixtures
Requires: greenlet
Requires: monotonic
Requires: oslo.concurrency
Requires: oslo.config
Requires: oslo.i18n
Requires: oslo.log
Requires: oslo.utils
Requires: six
Requires: yappi
BuildRequires : Paste
BuildRequires : PasteDeploy
BuildRequires : Routes
BuildRequires : WebOb
BuildRequires : buildreq-distutils3
BuildRequires : debtcollector
BuildRequires : eventlet
BuildRequires : fixtures
BuildRequires : greenlet
BuildRequires : monotonic
BuildRequires : oslo.concurrency
BuildRequires : oslo.config
BuildRequires : oslo.i18n
BuildRequires : oslo.log
BuildRequires : oslo.utils
BuildRequires : pbr
BuildRequires : six
BuildRequires : yappi

%description
========================
Team and repository tags
========================
.. image:: https://governance.openstack.org/tc/badges/oslo.service.svg
:target: https://governance.openstack.org/tc/ference/tags/index.html

%package license
Summary: license components for the oslo.service package.
Group: Default

%description license
license components for the oslo.service package.


%package python
Summary: python components for the oslo.service package.
Group: Default
Requires: oslo.service-python3 = %{version}-%{release}

%description python
python components for the oslo.service package.


%package python3
Summary: python3 components for the oslo.service package.
Group: Default
Requires: python3-core

%description python3
python3 components for the oslo.service package.


%prep
%setup -q -n oslo.service-1.40.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568320555
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/oslo.service
cp LICENSE %{buildroot}/usr/share/package-licenses/oslo.service/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/oslo.service/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
